theme: minima
title: Akseli Docs
description: Documentation for crow lab.
markdown: kramdown

# Exclude .py files and their folder
exclude:
  - _scripts/
  - _scripts/*
  - _config.yaml
  - images/
  - images/*

# Navigation for subpages
nav:
  - title: Home
    url: /
  - title: Kilosort
    url: /file1.md #fdas