theme: minima
title: Akseli Docs
description: Documentation for crow lab.
markdown: kramdown

# Custom CSS
sass:
  style: compressed

# Include custom CSS
include:
  - styles.css

# Navigation for subpages
nav:
  - title: Kilosort
    url: /2024-09-17-kilosort4.md

# MathJax support for LaTeX rendering
kramdown:
  math_engine: mathjax

# MathJax configuration
mathjax:
  config: "TeX-AMS-MML_HTMLorMML"
  tex2jax:
    inlineMath: [['$', '$'], ['\\(', '\\)']]
    displayMath: [['$$', '$$']]
    processEscapes: true